export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  EDITED_PRODUCT: "EDITED_PRODUCT",
  DELETED_PRODUCT: "DELETED_PRODUCT",
  ADDED_PRODUCT: "ADDED_PRODUCT",
};
