export const ActionTypes = {
  //for products
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  EDITED_PRODUCT: "EDITED_PRODUCT",
  DELETED_PRODUCT: "DELETED_PRODUCT",
  ADDED_PRODUCT: "ADDED_PRODUCT",

  //for modals
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  //for orders
  SET_ORDERS: "SET_ORDERS",
};
